name: Tests

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    env:
      PHP_COVERAGE_VERSION: '8.5'
      OS_COVERAGE: ubuntu-latest

    strategy:
        fail-fast: true
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            php: ['8.4', '8.5']

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: >
            dom,
            curl,
            fileinfo,
            libxml,
            mbstring,
            sodium,
            zip
          coverage: xdebug

      - name: Get Composer cache directory
        id: composer-cache
        shell: bash
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-
      
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        if: matrix.os != env.OS_COVERAGE
        run: composer test

      - name: Run tests with quality & coverage
        if: matrix.os == env.OS_COVERAGE
        run: composer check

      - name: Upload coverage reports to Codecov
        if: matrix.os == env.OS_COVERAGE && matrix.php == env.PHP_COVERAGE_VERSION
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}